config/routes.rb
Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable_entity'
  get '/500', to: 'errors#internal_server_error'

  namespace :admin do
    resources :schedules, only: %i[index create] do
      get :teacher_info, on: :collection
    end
  end

  root 'pages#home'
end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id         :bigint           not null, primary key
#  day        :date
#  end_time   :time
#  start_time :time
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  course_id  :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_schedules_on_course_id  (course_id)
#
class Schedule < ApplicationRecord
  include PublicActivity::Model
  tracked

  extend Enumerize

  # constants
  STATUS_COLLECTION = %i[finished cancelled on_going].freeze

  # associations
  belongs_to :teacher, class_name: 'User', foreign_key: 'user_id'
  belongs_to :course, counter_cache: true
  has_many :attendances, dependent: :destroy
  has_many :attendance_requests, dependent: :destroy

  # enumerize
  enumerize :status, in: STATUS_COLLECTION, default: :on_going, predicates: true, scope: true

  # validations
  validates :day, :start_time, :end_time, presence: true
  validate :end_must_be_after_start
  validate :cannot_overlap_times

  delegate :name, to: :course, prefix: true

  # scopes
  scope :where_students, ->(student) {
    joins(:attendances).where(attendances: { user_id: student.id })
  }
  scope :where_teacher, ->(teacher) { where(user_id: teacher.id) }
  scope :where_course, ->(course) { where(course_id: course.id) }
  scope :classes_today_region, ->(region_id) { joins(:teacher).where(day: Date.current, users: { region_id: }) }
  scope :where_teacher_course, ->(teacher, course) do
    scopes = [where_teacher(teacher), where_course(course)]
    where(id: scopes.flatten.map(&:id))
  end

  scope :in_range, ->(range) {
    where(
      'day = :day AND (user_id = :user_id OR course_id = :course_id) AND
      (
        (start_time BETWEEN :start AND :end) OR
        (end_time BETWEEN :start AND :end) OR
        (start_time <= :start AND end_time >= :end)
      )',
      start: (range.start_time.presence || (range.start_time + 1.minute)),
      end: (range.end_time.presence || (range.end_time - 1.minute)),
      day: range.day,
      course_id: range.course_id,
      user_id: range.user_id
    )
  }

  # methods
  def subject_name
    course.subject.name
  end

  private ##

  def cannot_overlap_times
    return if start_time.blank? && end_time.blank?

    amount = Schedule.count
    records = Schedule.where.not(id: [id, nil]).in_range(self)
    overlap_error if amount.positive? && records.present?
  end

  def overlap_error
    errors.add(:overlap_error, 'There is already an daterange in this times')
  end

  def end_must_be_after_start
    if start_time.present? && end_time.present? && start_time >= end_time
      errors.add(:end_time, 'must be after start date')
    end
  end
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < Admin::BaseController
  include DateTimeHelper
  before_action :prepare_index, only: %i[index]

  def index
    respond_to do |format|
      format.html
      format.json { render json: call_schedules_json, status: :ok }
    end
  end

  def teacher_info
    json_result = Admin::Schedules::PrepareTeacherDetailService.call(params)
    render json: json_result, status: :ok
  end

  def create
    schedule = Schedule.new(schedule_params)

    if schedule.save
      Admin::Schedules::InsertAttendancesService.call(schedule)
      flash_notice('common.create.success', 'schedule')
    else
      flash[:alert] = schedule.errors.full_messages.to_sentence
    end

    redirect_to admin_schedules_path
  end

  private ##

  def schedule_params
    params.require(:schedule).permit(
      :day, :course_id, :user_id, :start_time, :end_time
    )
  end

  def prepare_index
    hash = Admin::Schedules::PrepareIndexService.call(params, @current_region)
    @subjects = hash[:subjects]
    @schedules = hash[:schedules]
    @teachers = hash[:teachers]
  end

  def call_schedules_json
    params[:day] = date_normal_format_ymd(Date.current) if params[:day].blank?
    Admin::SchedulesJsonService.call(@schedules, params[:day])
  end
end

app/helpers/admin/schedules_helper.rb
module Admin::SchedulesHelper
  def hours_collection
    arr = (6..20)
    arr.step(0.5).map { |n| n.to_s.tr('.', ':').gsub(':5', ':30').gsub(':0', ':00') }
  end

  def check_hour_in_schedule(schedules, hour)
    schedules =
      schedules.pluck(:start_time, :end_time).map do |s|
        s.map { |a| a.strftime('%H.%M').to_f }
      end

    schedules.select { |s| hour.tr(':', '.').to_f.in?(s[0]..s[1]) }
  end

  def get_colour_from_find_subject(schedules, hour)
    color = ''

    schedules.map do |schedule|
      start_number = schedule.start_time.strftime('%H.%M').to_f
      end_number = schedule.end_time.strftime('%H.%M').to_f

      color = schedule.course.subject.color if hour.tr(':', '.').to_f.in?(start_number..end_number)
    end

    color
  end
end

app/views/admin/schedules/_table.slim
.card
  .table-responsive
    table.table.table-vcenter.table-mobile-md.card-table
      thead
        tr
          th Day
          th Start Time
          th End Time
          th Status
          th Teacher
          th.w-1
      tbody
        - schedules.each do |schedule|
          - teacher = schedule.teacher
          tr
            td data-label="Day"
              .font-weight-700 = date_normal_format(schedule.day)
            td data-label="Start Time"
              .font-weight-700 = time_format_24h(schedule.start_time)
            td data-label="End Time"
              span.font-weight-700 = time_format_24h(schedule.end_time)
            td data-label="Status"
              span.font-weight-700 = schedule_status_name(schedule.status)
            td data-label="Teacher info"
              .d-flex.py-1.align-items-center
                - avatar_url = teacher.avatar&.url
                - if avatar_url.blank?
                  span.avatar.avatar-sm.rounded-circle.me-2.border.border-warning.user-avatar
                    | S
                - else
                  = image_tag avatar_url, class: 'user-avatar rounded-circle me-2'
                = link_to admin_teacher_path(teacher.id), class: 'fw-bold text-blue width-content-10 text-ellipsis' do
                  = teacher&.name
            td
              .nav-item.dropdown.d-none.d-md-flex.me-3
                = render 'admin/shared/three_dot',
                          show_path: '#',
                          edit_path: '#',
                          remove_path: '#'

app/views/admin/schedules/index.slim
#schedules-index-container data-controller='schedules'
  .container-xl.bg-white.mb-4
    .d-block.d-md-flex.justify-content-between.mt-4
      .subjects-list-container.p-3
        h2 = Date.current.strftime('%B')
        p.m-0.text-muted = "Today is #{date_format_ordinalize_dmy_sort(Date.current)}"
        .d-flex.justify-content-between type="button" data-bs-toggle="collapse" data-bs-target="#collapseSubjects" aria-expanded="false" aria-controls="collapseSubjects" data-action='click->schedules#rotateIcon'
          span.w-100.font-weight-700.font-size-18 class="py-3"
            = "Programmes (#{@subjects.size})"
          = image_pack_tag 'icons/arrow-down-icon.svg'
        #collapseSubjects.collapse.show data-schedules-target='subjects'
          - @subjects.map do |subject|
            .row.subject-row.p-2 id="subject#{subject.id}"
              .d-inline-flex.align-items-center.justify-content-between
                .form-check.m-0
                  input.form-check-input type="checkbox" value=subject.id id="flexCheck-#{subject.id}" style="background-color: #{subject.color}" checked=true data-action='input->schedules#selectSubjects'
                  label.form-check-label.text-ellipsis for="flexCheck-#{subject.id}"
                    = subject.name
                .actions
                  a.nav-link.px-3[href='#' data-bs-toggle='dropdown' tabindex='-1' aria-label='Show actions']
                    = image_pack_tag 'icons/edit-icon.svg'
                  .dropdown-menu.dropdown-menu-arrow.dropdown-menu-end.dropdown-menu-card
                    .card
                      .list-group.list-group-flush.list-group-hoverable
                        a.list-group-item.cursor-pointer data-bs-toggle="modal" role="button" data-url=edit_admin_subject_path(subject) data-action='click->schedules#setDatasetSubjectForm'
                          .d-flex.col.text-truncate
                            = image_pack_tag 'icons/edit-icon.svg'
                            b.ms-2 Edit
                        a.list-group-item.cursor-pointer data-bs-toggle="modal" href="#modalDeleteSubject" role="button" data-url=admin_subject_path(subject) data-subject-id="subject#{subject.id}" data-action='click->schedules#setDatasetSubject'
                          = image_pack_tag 'icons/remove-icon.svg'
                          b.ms-2.text-red Remove
          button.btn.w-100.mt-3 data-bs-toggle="modal" type="button" data-url=new_admin_subject_path data-action='click->schedules#setDatasetSubjectForm'
            | Create new subject
      .calendar-container
        .header-toolbar.d-block.d-md-flex.justify-content-around.align-items-center.my-3
          .input-date
            .input-icon
              = image_pack_tag 'icons/calendar-icon.svg', class: 'input-icon-addon'
              input#date-picker-input.form-control.date-from type="text" placeholder="Select day" data-datepicker-target="input" data-action='change->schedules#filterByDay' value="#{date_normal_format_ymd(Date.current)}"
          .toolbar-center.d-flex.align-items-center
            span type='button' data-action='click->schedules#prevTime' data-schedules-target='prev'
              = image_pack_tag 'icons/chevron-left-icon.svg'
            h2.font-weight-700.font-size-16.mx-3.pt-2 data-day="#{params[:day].blank? ? date_normal_format_ymd(Date.current) : params[:day]}" data-schedules-target='date' = date_format_ordinalize_dmy(Date.current)
            span type='button' data-action='click->schedules#nextTime' data-schedules-target='next'
              = image_pack_tag 'icons/chevron-right-icon.svg'
          button.btn.btn-primary data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight" Create Schedule
        .fullcalendar-container data-schedules-target='calendar'
  #offcanvasRight.offcanvas.offcanvas-end tabindex="-1" aria-labelledby="offcanvasRightLabel"
    = render 'admin/schedules/offcanvas/offCanvas'
  #modalCreateSubject.modal.fade aria-hidden="true" aria-labelledby="staticBackdropLabel" tabindex="-1"
  #modalDeleteSubject.modal.fade[aria-hidden="true" aria-labelledby="modalDeleteSubject" tabindex="-1"]
    = render 'admin/subjects/confirm_first_modal'